name: PR Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@v1.0.2
        with:
          webhook: ${{ secrets.CAPTAIN_HOOK }}
          message: 'A new PR has been created: ${{ github.event.pull_request.html_url }}'
